### ISSUE TITLE
pointing to dotenv-vault@1.12.0 but this version is not published yet

### ISSUE THREAD

**Issue by reviewingcode** [dotenv-org/dotenv-vscode#22]
Unable to create a new vault / project, or login from the extension sidebar because apparently it is using `dotenv-vault` version `1.12.0` which does not exist at this point.

Latest published version of `dotenv-vault` is `1.11.2` - [changelog](https://github.com/dotenv-org/dotenv-vault/blob/master/CHANGELOG.md)

![Screenshot 2022-09-02 204045](https://user-images.githubusercontent.com/36093197/188191905-e942cbe1-d58e-4dd3-9b5e-4d4ed8f662f5.png)

**Comment by motdotla** [comment]
@reviewingcode apologies for this bug. Download `0.8.0`. It is fixed up there.

https://marketplace.visualstudio.com/items?itemName=dotenv.dotenv-vscode&ssr=false#overview
