### ISSUE TITLE
Do not treat IP addresses as numbers

### ISSUE THREAD

**Issue by martin-braun** [dotenv-org/dotenv-vscode#27]
Single or double quotes are optional in most cases, such as when using IP addresses. Unfortunately, the extension thinks the IP address is a number when no quotes are surrounded: 

<img width="162" alt="Screen Shot 2022-09-04 at 11 30 48 PM" src="https://user-images.githubusercontent.com/24259245/188334405-43634643-cbaf-4b46-bad2-77c2728f902d.png">

**Comment by motdotla** [comment]
Just a heads up that this will appear fixed - but that's because I've temporarily simplified the syntax highlighter. Still needs to be solved permanently.
