### ISSUE TITLE
Linux vscode: Link for toggling auto-cloaking doesn't show

### ISSUE THREAD

**Issue by ConnorJennison** [dotenv-org/dotenv-vscode#33]
Was working and found that on Linux vscode I'm not seeing the link in the .env file to toggle autocloaking that I see when I'm working on .env files on my Mac. I'm able to disable/enable autocloaking fine through command palette but might be good to look into this, or maybe also roll that toggle in to the .env sidebar item if possible

![Linux vscode image for reference](https://user-images.githubusercontent.com/17735436/191601308-63808303-8b57-4793-b275-e74a773ea537.png)

**Comment by chungweileong94** [comment]
In my case, the extension is pretty broken on my Mac, don't sure why is that
![image](https://user-images.githubusercontent.com/15154097/191651246-cfd8d47f-788b-4ee6-9bf4-335fbe45eb7e.png)

**Comment by tmwBuidls** [comment]
Same issue here is @chungweileong94

**Comment by chungweileong94** [comment]
After some digging, I found this workaround from #29, which fixed most of the issue I had with this extension, but still the link for toggling is still missing. Not sure if this is a bug from VSCode or this extension.

**Comment by motdotla** [comment]
@chungweileong94 and @tmwBuidls - apologies for that. We introduced a regression bug. It is fixed now on `0.11.0`.

Uninstall and re-install and things should work now.

https://marketplace.visualstudio.com/items?itemName=dotenv.dotenv-vscode

**Comment by motdotla** [comment]
@ConnorJennison can you try again on Linux vscode. Let me know if you still do not see the enable/disable auto-cloaking link.

**Comment by ConnorJennison** [comment]
Hey @motdotla I am seeing the toggle link at the top now!
