### ISSUE TITLE
Wrong syntax highlighting in .env.* files

### ISSUE THREAD

**Issue by danil0110** [dotenv-org/dotenv-vscode#67]
Syntax highlighting in the original `.env` file is OK. But if you append different environment names to it, e.g. `.env.production`, `.env.development`, or `.env.example` - it isn't correct.  

![CleanShot 2022-11-03 at 16 06 21@2x](https://user-images.githubusercontent.com/38916225/199742690-a4355496-19fc-4709-9696-0ef4563314e0.jpg)

**Comment by motdotla** [comment]
Thank you for reporting this @danil0110

**Comment by ConnorJennison** [comment]
Hey there. I'm working on reworking the syntax highlighting right now. Just as note I noticed for the normal .env file it would for some reason use the `properties` language for syntax highlighting, whereas other .env.* files would use `dotenv` language, which is why they look different.

**Comment by danil0110** [comment]
@ConnorJennison true, I've checked that. I've also noticed that, I guess, `dotenv` extension has a hardcoded variations of `.env` files. If I use `.env.development`, `.env.production`, `.env.example` - it sets language to `env`, but as soon as I create other files like `.env.sample`, `.env.random-name` - it sets language to `Plain Text`.

**Comment by danil0110** [comment]
@ConnorJennison I've made a little survey through some chats with developers. Here is the list with the names which are being used frequently:
- `.env.dev`
- `.env.development`
- `.env.prod`
- `.env.production`
- `.env.test`
- `.env.testing`
- `.env.local`
- `.env.stage`
- `.env.staging`
- `.env.deploy`
- `.env.deployment`
- `.env.example`
- `.env.sample`

**Comment by motdotla** [comment]
@danil0110, @ConnorJennison and I just released `0.21.0` that should fix these issues up.

Let us know if you still see anything. Thank you for reporting!

**Comment by danil0110** [comment]
@motdotla @ConnorJennison 
Nothing changed on my side
![CleanShot 2022-12-12 at 15 59 31@2x](https://user-images.githubusercontent.com/38916225/207064320-acea76df-91e5-4a7b-97d9-1aa65beec775.jpg)

**Comment by danil0110** [comment]
@motdotla @ConnorJennison any feedback?

**Comment by ConnorJennison** [comment]
Downloaded vscode on my windows laptop to test real quick and this is what I see for .env file

<img width="768" alt="dotenv-example" src="https://user-images.githubusercontent.com/17735436/208335917-9931c1f3-817d-4a5b-b3b3-beb6f5fc8784.png">

Can you check a couple of things for me.

1) Do `Control+K` `M` and make sure the language selected for those files is dotenv. It will say `configured language` next to that if being used for highlighting for that file.

2) Go into extension list and make sure that you are using version 0.21.0 (I think you should be able to check by clicking the `Install Another Version` button.

3) If neither of those did anything open the command pallete (`Control/CMD + Shift + P`) and type `scopes` and click the thing that comes up. Then you can click around the file and look at the textmate scopes for the different elements that will determine how it is highlighted. In your files if you click on `DATABASE` then the scope should be `variable.key.dotenv` and if you click on the string value for that key then the scopes should be `string.quoted.single.dotenv` and `property.value.dotenv`

Let me know if any of this solves it or if you're still seeing the same thing

**Comment by ConnorJennison** [comment]
re: the properties thing I noticed I named my test file `test.env`. I made a new one called just `.env` and that did configure to properties language at first, so that's likely why you're `.env` file looks different as well. I'm not sure what is causing that right now and I'll make an issue to track it, but I think you should be able to add an association to make a `.env` file load as  `dotenv` language as a workaround until I can track it down.

**Comment by danil0110** [comment]
Yes, everything is fine with `.env.*` files, they have `.env` language, the theme that I've been using has the same colors for vars and values so I thought it's a `dotenv` bug, sorry.
Except `.env` file, as you said, it has `properties` language.
