### ISSUE TITLE
Toggling Autocloaking causing workplace settings to change

### ISSUE THREAD

**Issue by DannyDelott** [dotenv-org/dotenv-vscode#73]
Autocloaking is great, but when I configure it in my User Settings then toggle it in my editor it always updates the Workplace Settings instead. We check our Workplace Settings into our repo and would prefer not to have this change show up when creating PRs.

**Comment by motdotla** [comment]
@DannyDelott is there another mechanism we could use to save state for these settings besides the workspace settings?

**Comment by DannyDelott** [comment]
User Settings would be a better option I think, since they don't typically get checked into the repo.

**Comment by motdotla** [comment]
I agree. 

`0.25.0` and greater now use user settings—no more workspace setting changes. If you experience it differently, please let me know.
