### ISSUE TITLE
Autocomplete only works with.env

### ISSUE THREAD

**Issue by toddgeist** [dotenv-org/dotenv-vscode#75]
Hi there,

Autocomplete seems to only work with `.env` files.

Is there a setting somewhere that I can use to get this to work with `.env.local`

Thanks :-)

**Comment by motdotla** [comment]
@toddgeist yes, that is correct.

We are trying to move the industry away from maintaining a separate `.env.local` file as it adds additional cognitive overhead and security risk. Now you have to manage a `.env` that IS committed to code and another that is NOT. (Vercel started an anti-pattern here by recommending and popularizing this.)

That said, can you add some more context here on how you are using it? 

@ConnorJennison and I will very much consider it and chime in with our thoughts.

**Comment by toddgeist** [comment]
It isn't a huge deal but, the most popular react framework and deployment platform, next.js and vercel, by default use .env.local, and .env isn't in the gitignore, when you set up a default new app. So you have to remember to add it otherwise it gets .env gets added to the repo.

If you want to shift the industry, I'd try to influence Next.js and Vercel.

Thanks for the response.  I'll go with .env and make sure it gets added to the gitignore for all the projects we have.

**Comment by motdotla** [comment]
> If you want to shift the industry, I'd try to influence Next.js and Vercel.

Indeed! working on that.
