### ISSUE TITLE
missing .env.fat

### ISSUE THREAD

**Issue by tjx666** [dotenv-org/dotenv-vscode#76]
<img width="412" alt="image" src="https://user-images.githubusercontent.com/41773861/206910870-a0ad5bd2-8e47-4e02-9ae3-bb8e0a7ffe41.png">

**Comment by motdotla** [comment]
Can you elaborate further? What does `.fat` relate to?

**Comment by tjx666** [comment]
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/41773861/206989107-b64506d7-3d1f-4377-ba90-2a07f14fddab.png">

I also donn't know the complete spelling, but that env means a test environmrnt.

**Comment by motdotla** [comment]
@ConnorJennison can you add support for this when you get time

**Comment by ConnorJennison** [comment]
Just saw this, will add to next push. Thanks for raising!

**Comment by ConnorJennison** [comment]
0.22.0 has been released and .env.fat files should now automatically use the dotEnv syntax highlighting!
