### ISSUE TITLE
.env file configuring to use properties langauge

### ISSUE THREAD

**Issue by ConnorJennison** [dotenv-org/dotenv-vscode#77]
For some reason files named exactly `.env` are auto-configuring to use the `properties` language instead of `dotenv` for syntax highlighting. Making this issue to be able to track this.

**Comment by jmevel** [comment]
If anybody is passing by here and wondering how to configure it in VS Code.
Add this in your settings file

```json
"files.associations": {
  ".env.*": "dotenv"
},
```

**Comment by motdotla** [comment]
Thank you @jmevel.

We're investigating to see if we can configure that setting as part of our extension so the user would not have to. We've configured languages.extensions already. Seems VScode extension have many configuration quirks.

**Comment by jmevel** [comment]
@motdotla thanks for your answer, yes I imagine it could sometimes be tricky to configure such thing in a VS Code extension. At least this issue has a workaround for now.

Thanks a lot for your work !

**Comment by motdotla** [comment]
I think `0.27.0` and greater solves this. Working well on my machine. It now sets `".env.*": "dotenv"` under `files.associations` in the user's settings.json
