### ISSUE TITLE
Auto-cloaking is replacing "editor.tokenColorCustomizations" settings

### ISSUE THREAD

**Issue by jcastrov** [dotenv-org/dotenv-vscode#79]
### Steps to Reproduce
1. Open any `.env` file and click on "Toogle auto-cloaking".

### Expected result
The auto-cloaking works and I keep my custom color customizations for other tokens defined in `"editor.tokenColorCustomizations"`

### Actual result
The auto-cloaking works, but I lose my custom color customizations for other tokens because the extension replaces all the content of `"editor.tokenColorCustomizations"`  in my User `settings.json`.

### Additional notes
This extension does what it says, but I don't want to lose my personal settings for other tokens I have defined. Not sure if this is a bug or a new feature.

### Issues related
https://github.com/dotenv-org/dotenv-vscode/issues/73

**Comment by ConnorJennison** [comment]
Thank you for the issue, will look into this

**Comment by ConnorJennison** [comment]
Working on this now, do you have an example settings.json file with some of the rules you have that I can use to test?

**Comment by motdotla** [comment]
This should be fixed in `0.24.3` and greater
