### ISSUE TITLE
Handle `=` in entry according to the parser

### ISSUE THREAD

**Issue by WoodyWoodsta** [dotenv-org/dotenv-vscode#84]
It's easy to break the current syntax highlighting by providing something like a base64 encoded string with `=` in it:

<img width="220" alt="image" src="https://user-images.githubusercontent.com/8268040/230419364-d8dcab66-24f2-4a09-be19-f17970867a5e.png">

I may be wrong but, at the least, anything between two `'` or `"` characters should be treated strictly as strings.

**Comment by WoodyWoodsta** [comment]
I've also noticed that there is a `dotenv.tmLanguage.json` and a dotenv-simple.tmLanguage.json`. I assume my setup is using the latter. Is there a way to switch to the actual highlighting file?

**Comment by WoodyWoodsta** [comment]
Actually, it's using the correct file. However, the regex here is wrong:

https://github.com/dotenv-org/dotenv-vscode/blob/master/syntaxes/dotenv.tmLanguage.json#L19

It should be `^\\s?(.*?)\\s?(\\=)(.*)$`, the first capture group should be lazy so as to capture only everything before the first `=`, not the last.

Could someone confirm that this is the correct parsing behaviour? I'll open a PR if correct.

**Comment by motdotla** [comment]
Yes, looks like you are correct @WoodyWoodsta. Please open that PR. Will be happy to merge. ✨
